### ISSUE TITLE
Změnit výchozí jazyk generovaných analytických zpráv na angličtinu

### ISSUE THREAD

**Issue by kliegr** [KIZI/EasyMiner-EasyMinerCenter#158]
Na easyminer.eu se generují analytické zprávy v češtině. Šablony podporovaly specifikování parametru, propagovaného z url, kterým se měnil jazyk na angličtinu.

**Comment by vojir** [comment]
Jazyk analytických zpráv se nově řídí jazykem uživatelského rozhraní.
