### ISSUE TITLE
Automatická konverze názvů souborů na neplatný formát

### ISSUE THREAD

**Issue by jindrichmynarz** [KIZI/EasyMiner-EasyMinerCenter#161]
Pokud uploaduji soubor s názvem v podtržítky, je jako jméno data source použit název s podtržítky nahrazenými pomlčkami. Ty ale nelze použít: *"Datasource name can contain only letters, numbers and underscore and start with a letter!"*

Řešení: nekonvertovat `snake_case` na `kebab-case`.

Testováno na [demu](https://easyminer-demo.lmcloud.vse.cz).

**Comment by vojir** [comment]
již opraveno v rámci #136
