### ISSUE TITLE
Chyba v replace generovaných adres pro MiningUI

### ISSUE THREAD

**Issue by PreVaDu** [KIZI/EasyMiner-EasyMinerCenter#179]
Na řádku
https://github.com/KIZI/EasyMiner-EasyMinerCenter/blob/master/app/EasyMinerModule/templates/MiningUi/config.latte#L223 chybí dvojité podtržítko u RULEIDS. Dle všeho nemá negativní vliv na funkčnost.

Pokud je možné již s kódem hýbat, klidně upravím sám.

**Comment by vojir** [comment]
Funkčnost to opravdu neovlivňovalo, ale děkuji za upozornění na chybu. Opraveno.
