### ISSUE TITLE
Nastavení datových typů na základě prvních x řádků souboru

### ISSUE THREAD

**Issue by kliegr** [KIZI/EasyMiner-EasyMinerCenter#54]
Nastavení datových typů na základě prvních x řádků souboru. Uživatel má mít možnost na stránce s importem přenastavit uhodnuté datové typy.  Datové typy jsou zobrazeny jako combo boxy pod řádkem se záhlavím sloupců. Výchozí počet načítaných řádků pro preview je 50 (současně se i zobrazují). Pro náhled uživateli měnit kódování jen v zobrazené části souboru.

**Comment by vojir** [comment]
Aktuálně není potřebné, bude řešeno v rámci integrace nové datové služby (issue #68)

**Comment by vojir** [comment]
vyřešeno v rámci řešení issue #68
